#
# Copyright (C) 2019, Northwestern University and Argonne National Laboratory
# See COPYRIGHT notice in top-level directory.
#
# $Id$
#
# @configure_input@

SUFFIXES += .o .c .cpp
AM_DEFAULT_SOURCE_EXT = .c

AM_CPPFLAGS += -I$(top_srcdir)/include
LDADD  += $(top_builddir)/lib/libbv-client.la

TESTPROGRAMS = tests/simple \
	       tests/strided \
               tests/null \
               tests/overlap

check_PROGRAMS += ${TESTPROGRAMS}

EXTRA_DIST += $(top_srcdir)/tests/wrap_runs.sh

OUT_FILES = $(check_PROGRAMS:%=%.bin)
SERVER_FILES = $(check_PROGRAMS:%=%.svc)

CLEANFILES += $(OUT_FILES) tests/core tests/core.* \
             $(SERVER_FILES)

LOG_COMPILER = $(top_srcdir)/tests/wrap_runs.sh

TESTS += ${TESTPROGRAMS}



